# ~/.tmuxinator/vlt.yml

name: vlt-oss
root: /Users/clint/go-src/github.com/hashicorp/vault

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: 

# Project hooks
# Runs on project start, always
#on_project_start: echo "on_project_start"
# Run on project start, the first time
#on_project_first_start: echo "on_project_first_start"
# Run on project start, after the first time
#on_project_restart: echo "on_project_restart"
# Run on project exit ( detaching from tmux session )
#on_project_exit: echo "on_project_exit"
# Run on project stop
#on_project_stop: echo "on_project_stop"

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window: envchain vlt $SHELL

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
startup_window: watch

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t stuff


windows:
  - watch: 
      layout: main-horizontal
      # layout: 1be4,255x56,0,0[255x37,0,0{127x37,0,0,1,127x37,128,0,3},255x18,0,38,4]]
      # layout: 1be4,255x56,0,0[255x37,0,0{127x37,0,0,1,127x37,128,0,3},255x18,0,38,4]
      panes:
        - 
        - daysuntil
  - gcp-auth:
      root: /Users/clint/go-src/github.com/hashicorp/vault-plugin-auth-gcp
      layout: main-horizontal
      panes:
        -
        -
  - gcp-common:
      root: /Users/clint/go-src/github.com/hashicorp/go-gcp-common
      layout: main-horizontal
      panes:
        -
        -